import {defineField, defineType} from 'sanity'
import {ImagesIcon} from '@sanity/icons/Images'

export const project = defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  icon: ImagesIcon,
  groups: [
    {name: 'main', title: 'Project', default: true},
    {name: 'photos', title: 'Photos'},
    {name: 'settings', title: 'Settings'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Project name',
      description: 'What was built, e.g. "Screened porch rebuild". Shows on the card and as the page heading.',
      type: 'string',
      group: 'main',
      validation: (rule) => rule.required().max(70),
    }),
    defineField({
      name: 'slug',
      title: 'Web address',
      description: 'Click Generate. This becomes stanskyconstruction.com/portfolio/…',
      type: 'slug',
      group: 'main',
      options: {source: 'title', maxLength: 80},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'One-sentence summary',
      description: 'Shown on project cards and in Google results.',
      type: 'text',
      rows: 2,
      group: 'main',
      validation: (rule) => rule.required().max(200),
    }),
    defineField({
      name: 'neighborhood',
      title: 'Neighborhood',
      description: 'E.g. "Buena Vista" or "Ardmore". Helps local search without giving away the address. Never enter a street address.',
      type: 'string',
      group: 'main',
    }),
    defineField({
      name: 'location',
      title: 'Town',
      description: 'Format: "Winston-Salem, NC".',
      type: 'string',
      group: 'main',
      validation: (rule) =>
        rule.regex(/^[A-Z][A-Za-z .'-]+, [A-Z]{2}$/, {name: 'Town, ST'}).warning('Use the format "Clemmons, NC".'),
    }),
    defineField({
      name: 'service',
      title: 'Type of work',
      type: 'reference',
      to: [{type: 'service'}],
      group: 'main',
    }),
    defineField({
      name: 'body',
      title: 'The story',
      description: 'A few sentences: what the client wanted, what you did, anything tricky you solved.',
      type: 'body',
      group: 'main',
    }),
    defineField({
      name: 'cover',
      title: 'Main photo',
      description: 'The best finished shot. Used on cards and when the page is shared.',
      type: 'photo',
      group: 'photos',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'before',
      title: '"Before" photo (optional)',
      description: 'If you add one, the main photo is shown as the "After".',
      type: 'photo',
      group: 'photos',
    }),
    defineField({
      name: 'gallery',
      title: 'More photos',
      type: 'array',
      of: [{type: 'photo'}],
      options: {layout: 'grid'},
      group: 'photos',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          {title: 'Complete', value: 'complete'},
          {title: 'In progress', value: 'in-progress'},
        ],
        layout: 'radio',
        direction: 'horizontal',
      },
      initialValue: 'complete',
      group: 'settings',
    }),
    defineField({
      name: 'featured',
      title: 'Show on the home page',
      type: 'boolean',
      initialValue: false,
      group: 'settings',
    }),
    defineField({
      name: 'order',
      title: 'Sort order',
      description: 'Lower numbers show first.',
      type: 'number',
      initialValue: 100,
      group: 'settings',
    }),
  ],
  orderings: [{title: 'Sort order', name: 'order', by: [{field: 'order', direction: 'asc'}]}],
  preview: {
    select: {title: 'title', neighborhood: 'neighborhood', location: 'location', media: 'cover'},
    prepare: ({title, neighborhood, location, media}) => ({
      title,
      subtitle: [neighborhood, location].filter(Boolean).join(', '),
      media,
    }),
  },
})
